package com.wizinno.shuhao.share.domain;

import com.wizinno.shuhao.share.domain.model.Share;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShareMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share
     *
     * @mbggenerated Wed Sep 27 15:39:44 CST 2017
     */
    int deleteByPrimaryKey(@Param("userId") Long userId, @Param("shareId") Long shareId, @Param("deviceId") Long deviceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share
     *
     * @mbggenerated Wed Sep 27 15:39:44 CST 2017
     */
    int insert(Share record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share
     *
     * @mbggenerated Wed Sep 27 15:39:44 CST 2017
     */
    Share selectByPrimaryKey(@Param("userId") Long userId, @Param("shareId") Long shareId, @Param("deviceId") Long deviceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share
     *
     * @mbggenerated Wed Sep 27 15:39:44 CST 2017
     */
    List<Share> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share
     *
     * @mbggenerated Wed Sep 27 15:39:44 CST 2017
     */
    int updateByPrimaryKey(Share record);

    List<Share> findByOrder(@Param("userId") Long userId, @Param("shareId") Long shareId, @Param("deviceId") Long deviceId);
}