package com.wizinno.shuhao.data.domain.model;

import java.io.Serializable;
import java.util.Date;

public class Data implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data.id
     *
     * @mbggenerated Wed Sep 27 11:36:54 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data.device_id
     *
     * @mbggenerated Wed Sep 27 11:36:54 CST 2017
     */
    private Long deviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data.receive_time
     *
     * @mbggenerated Wed Sep 27 11:36:54 CST 2017
     */
    private Date receiveTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data.data
     *
     * @mbggenerated Wed Sep 27 11:36:54 CST 2017
     */
    private String data;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table data
     *
     * @mbggenerated Wed Sep 27 11:36:54 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data.id
     *
     * @return the value of data.id
     *
     * @mbggenerated Wed Sep 27 11:36:54 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data.id
     *
     * @param id the value for data.id
     *
     * @mbggenerated Wed Sep 27 11:36:54 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data.device_id
     *
     * @return the value of data.device_id
     *
     * @mbggenerated Wed Sep 27 11:36:54 CST 2017
     */
    public Long getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data.device_id
     *
     * @param deviceId the value for data.device_id
     *
     * @mbggenerated Wed Sep 27 11:36:54 CST 2017
     */
    public void setDeviceId(Long deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data.receive_time
     *
     * @return the value of data.receive_time
     *
     * @mbggenerated Wed Sep 27 11:36:54 CST 2017
     */
    public Date getReceiveTime() {
        return receiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data.receive_time
     *
     * @param receiveTime the value for data.receive_time
     *
     * @mbggenerated Wed Sep 27 11:36:54 CST 2017
     */
    public void setReceiveTime(Date receiveTime) {
        this.receiveTime = receiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data.data
     *
     * @return the value of data.data
     *
     * @mbggenerated Wed Sep 27 11:36:54 CST 2017
     */
    public String getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data.data
     *
     * @param data the value for data.data
     *
     * @mbggenerated Wed Sep 27 11:36:54 CST 2017
     */
    public void setData(String data) {
        this.data = data == null ? null : data.trim();
    }
}