package com.wizinno.shuhao.data.domain;

import com.wizinno.shuhao.condition.DataCondition;
import com.wizinno.shuhao.data.domain.model.Data;
import org.apache.ibatis.annotations.Param;

import java.util.Date;
import java.util.List;

public interface DataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data
     *
     * @mbggenerated Wed Sep 27 11:36:54 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data
     *
     * @mbggenerated Wed Sep 27 11:36:54 CST 2017
     */
    int insert(Data record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data
     *
     * @mbggenerated Wed Sep 27 11:36:54 CST 2017
     */
    Data selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data
     *
     * @mbggenerated Wed Sep 27 11:36:54 CST 2017
     */
    List<Data> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data
     *
     * @mbggenerated Wed Sep 27 11:36:54 CST 2017
     */
    int updateByPrimaryKey(Data record);

    List<Data> finByDeviceId(@Param("deviceId") Long deviceId, @Param("records") int records);

    List<Data> findAllByDeviceId(@Param("deviceId") Long deviceId);

   Data isFinByDeviceId(@Param("deviceId") Long deviceId);

    List<Data> finByDeviceIdAndTime(DataCondition con);

    List<Data> getDatasManage(DataCondition con);

    Long getDatasManageTotal(DataCondition con);
}