package com.wizinno.shuhao.device.domain.model;

import java.io.Serializable;
import java.util.Date;

public class Device implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.device_id
     *
     * @mbggenerated Tue Nov 07 17:14:04 CST 2017
     */
    private Long deviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.device_ver
     *
     * @mbggenerated Tue Nov 07 17:14:04 CST 2017
     */
    private String deviceVer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.sensor_count
     *
     * @mbggenerated Tue Nov 07 17:14:04 CST 2017
     */
    private Integer sensorCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.driver_count
     *
     * @mbggenerated Tue Nov 07 17:14:04 CST 2017
     */
    private Integer driverCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.io_cfg
     *
     * @mbggenerated Tue Nov 07 17:14:04 CST 2017
     */
    private String ioCfg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.sampling_period
     *
     * @mbggenerated Tue Nov 07 17:14:04 CST 2017
     */
    private Integer samplingPeriod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.io_cfg_time
     *
     * @mbggenerated Tue Nov 07 17:14:04 CST 2017
     */
    private Date ioCfgTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.is_online
     *
     * @mbggenerated Tue Nov 07 17:14:04 CST 2017
     */
    private Integer isOnline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.online_time
     *
     * @mbggenerated Tue Nov 07 17:14:04 CST 2017
     */
    private Date onlineTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.sinario_cfg
     *
     * @mbggenerated Tue Nov 07 17:14:04 CST 2017
     */
    private String sinarioCfg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.sinario_cfg_time
     *
     * @mbggenerated Tue Nov 07 17:14:04 CST 2017
     */
    private Date sinarioCfgTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.user_id
     *
     * @mbggenerated Tue Nov 07 17:14:04 CST 2017
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.user_phone
     *
     * @mbggenerated Tue Nov 07 17:14:04 CST 2017
     */
    private String userPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table device
     *
     * @mbggenerated Tue Nov 07 17:14:04 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.device_id
     *
     * @return the value of device.device_id
     *
     * @mbggenerated Tue Nov 07 17:14:04 CST 2017
     */
    public Long getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.device_id
     *
     * @param deviceId the value for device.device_id
     *
     * @mbggenerated Tue Nov 07 17:14:04 CST 2017
     */
    public void setDeviceId(Long deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.device_ver
     *
     * @return the value of device.device_ver
     *
     * @mbggenerated Tue Nov 07 17:14:04 CST 2017
     */
    public String getDeviceVer() {
        return deviceVer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.device_ver
     *
     * @param deviceVer the value for device.device_ver
     *
     * @mbggenerated Tue Nov 07 17:14:04 CST 2017
     */
    public void setDeviceVer(String deviceVer) {
        this.deviceVer = deviceVer == null ? null : deviceVer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.sensor_count
     *
     * @return the value of device.sensor_count
     *
     * @mbggenerated Tue Nov 07 17:14:04 CST 2017
     */
    public Integer getSensorCount() {
        return sensorCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.sensor_count
     *
     * @param sensorCount the value for device.sensor_count
     *
     * @mbggenerated Tue Nov 07 17:14:04 CST 2017
     */
    public void setSensorCount(Integer sensorCount) {
        this.sensorCount = sensorCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.driver_count
     *
     * @return the value of device.driver_count
     *
     * @mbggenerated Tue Nov 07 17:14:04 CST 2017
     */
    public Integer getDriverCount() {
        return driverCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.driver_count
     *
     * @param driverCount the value for device.driver_count
     *
     * @mbggenerated Tue Nov 07 17:14:04 CST 2017
     */
    public void setDriverCount(Integer driverCount) {
        this.driverCount = driverCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.io_cfg
     *
     * @return the value of device.io_cfg
     *
     * @mbggenerated Tue Nov 07 17:14:04 CST 2017
     */
    public String getIoCfg() {
        return ioCfg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.io_cfg
     *
     * @param ioCfg the value for device.io_cfg
     *
     * @mbggenerated Tue Nov 07 17:14:04 CST 2017
     */
    public void setIoCfg(String ioCfg) {
        this.ioCfg = ioCfg == null ? null : ioCfg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.sampling_period
     *
     * @return the value of device.sampling_period
     *
     * @mbggenerated Tue Nov 07 17:14:04 CST 2017
     */
    public Integer getSamplingPeriod() {
        return samplingPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.sampling_period
     *
     * @param samplingPeriod the value for device.sampling_period
     *
     * @mbggenerated Tue Nov 07 17:14:04 CST 2017
     */
    public void setSamplingPeriod(Integer samplingPeriod) {
        this.samplingPeriod = samplingPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.io_cfg_time
     *
     * @return the value of device.io_cfg_time
     *
     * @mbggenerated Tue Nov 07 17:14:04 CST 2017
     */
    public Date getIoCfgTime() {
        return ioCfgTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.io_cfg_time
     *
     * @param ioCfgTime the value for device.io_cfg_time
     *
     * @mbggenerated Tue Nov 07 17:14:04 CST 2017
     */
    public void setIoCfgTime(Date ioCfgTime) {
        this.ioCfgTime = ioCfgTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.is_online
     *
     * @return the value of device.is_online
     *
     * @mbggenerated Tue Nov 07 17:14:04 CST 2017
     */
    public Integer getIsOnline() {
        return isOnline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.is_online
     *
     * @param isOnline the value for device.is_online
     *
     * @mbggenerated Tue Nov 07 17:14:04 CST 2017
     */
    public void setIsOnline(Integer isOnline) {
        this.isOnline = isOnline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.online_time
     *
     * @return the value of device.online_time
     *
     * @mbggenerated Tue Nov 07 17:14:04 CST 2017
     */
    public Date getOnlineTime() {
        return onlineTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.online_time
     *
     * @param onlineTime the value for device.online_time
     *
     * @mbggenerated Tue Nov 07 17:14:04 CST 2017
     */
    public void setOnlineTime(Date onlineTime) {
        this.onlineTime = onlineTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.sinario_cfg
     *
     * @return the value of device.sinario_cfg
     *
     * @mbggenerated Tue Nov 07 17:14:04 CST 2017
     */
    public String getSinarioCfg() {
        return sinarioCfg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.sinario_cfg
     *
     * @param sinarioCfg the value for device.sinario_cfg
     *
     * @mbggenerated Tue Nov 07 17:14:04 CST 2017
     */
    public void setSinarioCfg(String sinarioCfg) {
        this.sinarioCfg = sinarioCfg == null ? null : sinarioCfg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.sinario_cfg_time
     *
     * @return the value of device.sinario_cfg_time
     *
     * @mbggenerated Tue Nov 07 17:14:04 CST 2017
     */
    public Date getSinarioCfgTime() {
        return sinarioCfgTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.sinario_cfg_time
     *
     * @param sinarioCfgTime the value for device.sinario_cfg_time
     *
     * @mbggenerated Tue Nov 07 17:14:04 CST 2017
     */
    public void setSinarioCfgTime(Date sinarioCfgTime) {
        this.sinarioCfgTime = sinarioCfgTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.user_id
     *
     * @return the value of device.user_id
     *
     * @mbggenerated Tue Nov 07 17:14:04 CST 2017
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.user_id
     *
     * @param userId the value for device.user_id
     *
     * @mbggenerated Tue Nov 07 17:14:04 CST 2017
     */
    public void setUserId(Long userId) {
        this.userId = userId ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.user_phone
     *
     * @return the value of device.user_phone
     *
     * @mbggenerated Tue Nov 07 17:14:04 CST 2017
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.user_phone
     *
     * @param userPhone the value for device.user_phone
     *
     * @mbggenerated Tue Nov 07 17:14:04 CST 2017
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone == null ? null : userPhone.trim();
    }
}