package com.wizinno.shuhao.device.domain;

import com.wizinno.shuhao.condition.DeviceCondition;
import com.wizinno.shuhao.device.domain.model.Device;
import java.util.List;

public interface DeviceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbggenerated Tue Nov 07 17:14:04 CST 2017
     */
    int deleteByPrimaryKey(Long deviceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbggenerated Tue Nov 07 17:14:04 CST 2017
     */
    int insert(Device record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbggenerated Tue Nov 07 17:14:04 CST 2017
     */
    Device selectByPrimaryKey(Long deviceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbggenerated Tue Nov 07 17:14:04 CST 2017
     */
    List<Device> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbggenerated Tue Nov 07 17:14:04 CST 2017
     */
    int updateByPrimaryKey(Device record);

    List<Device> isBindDevice(Long userId);

    List<Device> getDevices(DeviceCondition con);

    Long getDevicesTotal(DeviceCondition con);
}