package com.wizinno.shuhao.user.domain;

import com.wizinno.shuhao.user.data.AppVerDto;
import com.wizinno.shuhao.user.domain.model.AppVer;
import java.util.List;

public interface AppVerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_ver
     *
     * @mbggenerated Thu Sep 28 14:54:28 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_ver
     *
     * @mbggenerated Thu Sep 28 14:54:28 CST 2017
     */
    int insert(AppVer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_ver
     *
     * @mbggenerated Thu Sep 28 14:54:28 CST 2017
     */
    AppVer selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_ver
     *
     * @mbggenerated Thu Sep 28 14:54:28 CST 2017
     */
    List<AppVer> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_ver
     *
     * @mbggenerated Thu Sep 28 14:54:28 CST 2017
     */
    int updateByPrimaryKey(AppVer record);

    List<AppVer> getNewApp(Integer platform);


    List<AppVer> getAppVers();
}