package com.wizinno.shuhao.user.domain;

import com.wizinno.shuhao.user.domain.model.AuthoCode;
import java.util.List;

public interface AuthoCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table autho_code
     *
     * @mbggenerated Mon Oct 23 12:50:30 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table autho_code
     *
     * @mbggenerated Mon Oct 23 12:50:30 CST 2017
     */
    int insert(AuthoCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table autho_code
     *
     * @mbggenerated Mon Oct 23 12:50:30 CST 2017
     */
    AuthoCode selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table autho_code
     *
     * @mbggenerated Mon Oct 23 12:50:30 CST 2017
     */
    List<AuthoCode> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table autho_code
     *
     * @mbggenerated Mon Oct 23 12:50:30 CST 2017
     */
    int updateByPrimaryKey(AuthoCode record);

    AuthoCode selectByPhone(String phone);

    int updateByPhone(AuthoCode record);
}