package com.wizinno.shuhao.user.domain;

import com.wizinno.shuhao.condition.LogCondition;
import com.wizinno.shuhao.user.domain.model.Log;
import java.util.List;

public interface LogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated Wed Nov 08 14:24:12 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated Wed Nov 08 14:24:12 CST 2017
     */
    int insert(Log record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated Wed Nov 08 14:24:12 CST 2017
     */
    Log selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated Wed Nov 08 14:24:12 CST 2017
     */
    List<Log> selectAll(LogCondition logCondition);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated Wed Nov 08 14:24:12 CST 2017
     */
    int updateByPrimaryKey(Log record);

    List<Log> queryByCondition(LogCondition logCondition);
}