package com.wizinno.shuhao.user.domain;

import com.wizinno.shuhao.user.domain.model.UserFriends;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserFriendsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friends
     *
     * @mbggenerated Tue Sep 26 13:42:19 CST 2017
     */
    int deleteByPrimaryKey(@Param("userId") Long userId, @Param("friendId") Long friendId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friends
     *
     * @mbggenerated Tue Sep 26 13:42:19 CST 2017
     */
    int insert(UserFriends record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friends
     *
     * @mbggenerated Tue Sep 26 13:42:19 CST 2017
     */
    List<UserFriends> selectAll();
}