package com.wizinno.shuhao.user.domain;

import com.wizinno.shuhao.condition.UserCondition;
import com.wizinno.shuhao.device.data.DeviceDto;
import com.wizinno.shuhao.user.domain.model.User;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Sep 19 18:27:55 CST 2017
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Sep 19 18:27:55 CST 2017
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Sep 19 18:27:55 CST 2017
     */
    User selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Sep 19 18:27:55 CST 2017
     */
    List<User> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Sep 19 18:27:55 CST 2017
     */
    int updateByPrimaryKey(User record);

    User selectByPhone(String phone);

    List<User> getFriends(Long userId);


    Long getUsersTotal(UserCondition con);

    List<User> getUsers(UserCondition con);

    List<DeviceDto> getDevicesByUserId(UserCondition con);

    Long getDevicesByUserIdTotal(UserCondition con);

    List<User> getFriendsByUserId(UserCondition con);

    Long getFriendsByUserIdTotal(UserCondition con);

    List<Long> getUserShares(@Param("userId") Long userId,@Param("friendId") Long friendId);

    List<Long> getFriendShares(@Param("friendId") Long friendId,@Param("userId") Long userId);

    List<DeviceDto> getFriendDevicesShares(UserCondition con);

    Long getFriendDevicesSharesTotal(UserCondition con);
}