package com.wizinno.shuhao.user.domain.model;

import java.io.Serializable;
import java.util.Date;

public class AppVer implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_ver.id
     *
     * @mbggenerated Thu Sep 28 14:54:28 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_ver.platform
     *
     * @mbggenerated Thu Sep 28 14:54:28 CST 2017
     */
    private Integer platform;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_ver.app_ver
     *
     * @mbggenerated Thu Sep 28 14:54:28 CST 2017
     */
    private Integer appVer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_ver.desc
     *
     * @mbggenerated Thu Sep 28 14:54:28 CST 2017
     */
    private String describ;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_ver.rel_time
     *
     * @mbggenerated Thu Sep 28 14:54:28 CST 2017
     */
    private Date relTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_ver.url
     *
     * @mbggenerated Thu Sep 28 14:54:28 CST 2017
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table app_ver
     *
     * @mbggenerated Thu Sep 28 14:54:28 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_ver.id
     *
     * @return the value of app_ver.id
     *
     * @mbggenerated Thu Sep 28 14:54:28 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_ver.id
     *
     * @param id the value for app_ver.id
     *
     * @mbggenerated Thu Sep 28 14:54:28 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_ver.platform
     *
     * @return the value of app_ver.platform
     *
     * @mbggenerated Thu Sep 28 14:54:28 CST 2017
     */
    public Integer getPlatform() {
        return platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_ver.platform
     *
     * @param platform the value for app_ver.platform
     *
     * @mbggenerated Thu Sep 28 14:54:28 CST 2017
     */
    public void setPlatform(Integer platform) {
        this.platform = platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_ver.app_ver
     *
     * @return the value of app_ver.app_ver
     *
     * @mbggenerated Thu Sep 28 14:54:28 CST 2017
     */
    public Integer getAppVer() {
        return appVer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_ver.app_ver
     *
     * @param appVer the value for app_ver.app_ver
     *
     * @mbggenerated Thu Sep 28 14:54:28 CST 2017
     */
    public void setAppVer(Integer appVer) {
        this.appVer = appVer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_ver.desc
     *
     * @return the value of app_ver.desc
     *
     * @mbggenerated Thu Sep 28 14:54:28 CST 2017
     */
    public String getDescrib() {
        return describ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_ver.describ
     *
     * @param describ the value for app_ver.describ
     *
     * @mbggenerated Thu Sep 28 14:54:28 CST 2017
     */
    public void setDescrib(String describ) {
        this.describ = describ == null ? null : describ.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_ver.rel_time
     *
     * @return the value of app_ver.rel_time
     *
     * @mbggenerated Thu Sep 28 14:54:28 CST 2017
     */
    public Date getRelTime() {
        return relTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_ver.rel_time
     *
     * @param relTime the value for app_ver.rel_time
     *
     * @mbggenerated Thu Sep 28 14:54:28 CST 2017
     */
    public void setRelTime(Date relTime) {
        this.relTime = relTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_ver.url
     *
     * @return the value of app_ver.url
     *
     * @mbggenerated Thu Sep 28 14:54:28 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_ver.url
     *
     * @param url the value for app_ver.url
     *
     * @mbggenerated Thu Sep 28 14:54:28 CST 2017
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }
}