package com.wizinno.shuhao.user.domain.model;

import java.io.Serializable;

public class AuthoCode implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column autho_code.id
     *
     * @mbggenerated Mon Oct 23 12:50:30 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column autho_code.phone
     *
     * @mbggenerated Mon Oct 23 12:50:30 CST 2017
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column autho_code.autho_code
     *
     * @mbggenerated Mon Oct 23 12:50:30 CST 2017
     */
    private String authoCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table autho_code
     *
     * @mbggenerated Mon Oct 23 12:50:30 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column autho_code.id
     *
     * @return the value of autho_code.id
     *
     * @mbggenerated Mon Oct 23 12:50:30 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column autho_code.id
     *
     * @param id the value for autho_code.id
     *
     * @mbggenerated Mon Oct 23 12:50:30 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column autho_code.phone
     *
     * @return the value of autho_code.phone
     *
     * @mbggenerated Mon Oct 23 12:50:30 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column autho_code.phone
     *
     * @param phone the value for autho_code.phone
     *
     * @mbggenerated Mon Oct 23 12:50:30 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column autho_code.autho_code
     *
     * @return the value of autho_code.autho_code
     *
     * @mbggenerated Mon Oct 23 12:50:30 CST 2017
     */
    public String getAuthoCode() {
        return authoCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column autho_code.autho_code
     *
     * @param authoCode the value for autho_code.autho_code
     *
     * @mbggenerated Mon Oct 23 12:50:30 CST 2017
     */
    public void setAuthoCode(String authoCode) {
        this.authoCode = authoCode == null ? null : authoCode.trim();
    }
}