package com.wizinno.shuhao.user.domain.model;

import java.io.Serializable;
import java.util.Date;

public class Log implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.id
     *
     * @mbggenerated Wed Nov 08 14:24:12 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.op_time
     *
     * @mbggenerated Wed Nov 08 14:24:12 CST 2017
     */
    private Date opTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.user_id
     *
     * @mbggenerated Wed Nov 08 14:24:12 CST 2017
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.user_name
     *
     * @mbggenerated Wed Nov 08 14:24:12 CST 2017
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.ip_addr
     *
     * @mbggenerated Wed Nov 08 14:24:12 CST 2017
     */
    private String ipAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.app_ver
     *
     * @mbggenerated Wed Nov 08 14:24:12 CST 2017
     */
    private String appVer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.event
     *
     * @mbggenerated Wed Nov 08 14:24:12 CST 2017
     */
    private String event;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.url
     *
     * @mbggenerated Wed Nov 08 14:24:12 CST 2017
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.request
     *
     * @mbggenerated Wed Nov 08 14:24:12 CST 2017
     */
    private String request;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.response
     *
     * @mbggenerated Wed Nov 08 14:24:12 CST 2017
     */
    private String response;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table log
     *
     * @mbggenerated Wed Nov 08 14:24:12 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.id
     *
     * @return the value of log.id
     *
     * @mbggenerated Wed Nov 08 14:24:12 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.id
     *
     * @param id the value for log.id
     *
     * @mbggenerated Wed Nov 08 14:24:12 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.op_time
     *
     * @return the value of log.op_time
     *
     * @mbggenerated Wed Nov 08 14:24:12 CST 2017
     */
    public Date getOpTime() {
        return opTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.op_time
     *
     * @param opTime the value for log.op_time
     *
     * @mbggenerated Wed Nov 08 14:24:12 CST 2017
     */
    public void setOpTime(Date opTime) {
        this.opTime = opTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.user_id
     *
     * @return the value of log.user_id
     *
     * @mbggenerated Wed Nov 08 14:24:12 CST 2017
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.user_id
     *
     * @param userId the value for log.user_id
     *
     * @mbggenerated Wed Nov 08 14:24:12 CST 2017
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.user_name
     *
     * @return the value of log.user_name
     *
     * @mbggenerated Wed Nov 08 14:24:12 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.user_name
     *
     * @param userName the value for log.user_name
     *
     * @mbggenerated Wed Nov 08 14:24:12 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.ip_addr
     *
     * @return the value of log.ip_addr
     *
     * @mbggenerated Wed Nov 08 14:24:12 CST 2017
     */
    public String getIpAddr() {
        return ipAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.ip_addr
     *
     * @param ipAddr the value for log.ip_addr
     *
     * @mbggenerated Wed Nov 08 14:24:12 CST 2017
     */
    public void setIpAddr(String ipAddr) {
        this.ipAddr = ipAddr == null ? null : ipAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.app_ver
     *
     * @return the value of log.app_ver
     *
     * @mbggenerated Wed Nov 08 14:24:12 CST 2017
     */
    public String getAppVer() {
        return appVer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.app_ver
     *
     * @param appVer the value for log.app_ver
     *
     * @mbggenerated Wed Nov 08 14:24:12 CST 2017
     */
    public void setAppVer(String appVer) {
        this.appVer = appVer == null ? null : appVer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.event
     *
     * @return the value of log.event
     *
     * @mbggenerated Wed Nov 08 14:24:12 CST 2017
     */
    public String getEvent() {
        return event;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.event
     *
     * @param event the value for log.event
     *
     * @mbggenerated Wed Nov 08 14:24:12 CST 2017
     */
    public void setEvent(String event) {
        this.event = event == null ? null : event.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.url
     *
     * @return the value of log.url
     *
     * @mbggenerated Wed Nov 08 14:24:12 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.url
     *
     * @param url the value for log.url
     *
     * @mbggenerated Wed Nov 08 14:24:12 CST 2017
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.request
     *
     * @return the value of log.request
     *
     * @mbggenerated Wed Nov 08 14:24:12 CST 2017
     */
    public String getRequest() {
        return request;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.request
     *
     * @param request the value for log.request
     *
     * @mbggenerated Wed Nov 08 14:24:12 CST 2017
     */
    public void setRequest(String request) {
        this.request = request == null ? null : request.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.response
     *
     * @return the value of log.response
     *
     * @mbggenerated Wed Nov 08 14:24:12 CST 2017
     */
    public String getResponse() {
        return response;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.response
     *
     * @param response the value for log.response
     *
     * @mbggenerated Wed Nov 08 14:24:12 CST 2017
     */
    public void setResponse(String response) {
        this.response = response == null ? null : response.trim();
    }
}